churn_elt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: churnuser
      password: churnpassword
      port: 5432
      dbname: customer
      schema: analytics
      threads: 1